#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# (c) Grupo AIA
#     marinjl@aia.es
#

from dynawo_validation.dynaflow.pipeline import run_pipeline
import argparse
import sys

parser = argparse.ArgumentParser()
parser.add_argument("base_case")
parser.add_argument("results_dir")
parser.add_argument(
    "-A",
    "--launcherA",
    default="dynawo.sh",
    help="Defines the launcher of simulator A",
)
parser.add_argument(
    "-B",
    "--launcherB",
    default="dynawo.sh",
    help="Defines the launcher of simulator B",
)
parser.add_argument(
    "-a",
    "--allcontg",
    action="store_true",
    help="Run all the contingencies",
)

args = parser.parse_args()


def main():
    run_pipeline.run_pipeline(
        args.base_case, args.results_dir, args.launcherA, args.launcherB, args.allcontg
    )


if __name__ == "__main__":
    sys.exit(main())
