#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# (c) Grupo AIA
#     marinjl@aia.es
#

from dynawo_validation.dynawaltz.pipeline import run_pipeline
import argparse
import sys

parser = argparse.ArgumentParser()
parser.add_argument("base_case")
parser.add_argument("results_dir")
parser.add_argument(
    "-A",
    "--launcherA",
    default="dynawo.sh",
)
parser.add_argument(
    "-B",
    "--launcherB",
    default="dynawo.sh",
)
args = parser.parse_args()


def main():
    run_pipeline.run_pipeline(
        args.base_case, args.results_dir, args.launcherA, args.launcherB
    )


if __name__ == "__main__":
    sys.exit(main())
