#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# (c) Grupo AIA
#     marinjl@aia.es
#

from dynawo_validation.dynawaltz.pipeline import run_pipeline
import argparse
import sys

parser = argparse.ArgumentParser()
parser.add_argument("base_case")
parser.add_argument("results_dir")
args = parser.parse_args()


def main():
    run_pipeline.run_pipeline(args.base_case, args.results_dir)


if __name__ == "__main__":
    sys.exit(main())
