#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# (c) Grupo AIA
#     marinjl@aia.es
#

from dynawo_validation.commons import extract_bus
import sys
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("iidm_file", help="enter the iidm file")
parser.add_argument("bus_name", help="enter the bus name")
args = parser.parse_args()

def main():
    extract_bus.extract_bus(args.iidm_file, args.bus_name)


if __name__ == "__main__":
    sys.exit(main())
