#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# (c) Grupo AIA
#     marinjl@aia.es
#

from dynawo_validation.commons import find_src_path
import sys


def main():
    find_src_path.find_path()


if __name__ == "__main__":
    sys.exit(main())
